log_filename = "webgui1.log"
user_db = "database/users.toml"
grain_db = "database/grain.toml"
matlab_exec = "/Applications/MATLAB_R2018a.app/bin/matlab"
matlab_folder = "/Users/willi/tmp/FT_model_180419"
